version: '3'

services:

  db:
    image: postgres

  web:
    build: .
    # TODO (gdingle): use gunicorn for prod
    # remeber to run: docker-compose exec web python manage.py migrate
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    # For pdb
    stdin_open: true
    tty: true