version: '3'

services:

  db:
    image: postgres

  crispresso:
    build: crispresso
    command: python app.py
    volumes:
      - ./crispresso:/code
    ports:
      - "5000:5000"

  web:
    build: .
    # TODO (gdingle): use gunicorn for prod
    # TODO (gdingle): python3 manage.py migrate here??
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - crispresso
    # For pdb
    stdin_open: true
    tty: true