# Generated by Django 2.1.1 on 2018-11-08 22:30

from django.db import migrations


def insert_exp_for_custom_analysis(apps, schema_editor):
    Experiment = apps.get_model('main', 'Experiment')
    exp = Experiment(name='No experiment -- Custom analysis')
    exp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_exp_for_custom_analysis),
    ]
