# Generated by Django 2.1.1 on 2018-09-17 23:40

from lib import validators

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='s3_bucket',
            field=models.CharField(default='ryan.leenay-bucket', max_length=80),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='s3_prefix',
            field=models.CharField(default='Greg_CXCR4_iPSC', max_length=160),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='hdr_seq',
            field=models.CharField(blank=True, help_text='Sequence for Homology Directed Repair', max_length=65536, validators=[validators.validate_chr_or_seq_or_enst_or_gene]),
        ),
    ]
