# Generated by Django 2.0.7 on 2018-07-23 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('pcr_file', models.FileField(blank=True, null=True, upload_to='')),
                ('read_length', models.IntegerField(default=250, help_text='What is the read length used in the experiment?')),
                ('fragment_length', models.IntegerField(default=300, help_text='What is average fragment length (before adapters)?')),
                ('stdev_fragment_length', models.IntegerField(default=45, help_text='What is the standard deviation of the fragment legnths? If unknown, assume 10% of the average.')),
            ],
        ),
        migrations.RemoveField(
            model_name='samplesheet',
            name='guide_selection',
        ),
        migrations.RemoveField(
            model_name='samplesheet',
            name='primer_selection',
        ),
        migrations.AlterModelOptions(
            name='experiment',
            options={'ordering': ['-id']},
        ),
        migrations.DeleteModel(
            name='SampleSheet',
        ),
        migrations.AddField(
            model_name='analysis',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Experiment'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Researcher'),
        ),
    ]
