# Generated by Django 2.1 on 2018-08-07 22:47

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180723_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='fragment_length',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='pcr_file',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='read_length',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='stdev_fragment_length',
        ),
        migrations.AddField(
            model_name='analysis',
            name='amplicon_seq',
            field=models.CharField(default='cgaggagatacaggcggagggcgaggagatacaggcggagggcgaggagatacaggcggagagcgGCGCTAGGACCCGCCGGCCACCCCGCCGGCTCCCGGGAGGTTGATAAAGCGGCGGCGGCGTTTGACGTCAGTGGGGAGTTAATTTTAAATCGGTACAAGATGGCGGAGGGGGACGAGGCAGCGCGAGGGCAGCAACCGCACCAGGGGCTGTGGCGCCGGCGACGGACCAGCGACCCAAGCGCCGCGGTTAACCACGTCTCGTCCAC', max_length=65536),
        ),
        migrations.AddField(
            model_name='analysis',
            name='results_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='s3_bucket',
            field=models.CharField(default='jasonli-bucket', max_length=80),
        ),
        migrations.AddField(
            model_name='analysis',
            name='s3_prefix',
            field=models.CharField(default='JasonHDR/96wp1sorted-fastq/', max_length=160),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='targets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=65536, validators=[main.validators.validate_chr_or_seq_or_enst]), default=['chr7:5569176-5569415', 'chr1:11,130,540-11,130,751'], help_text='Chr location or seq or ENST, one per line. Tag-in experiments require ENST.', size=None),
        ),
    ]
