# Generated by Django 2.1.1 on 2018-11-09 02:46

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20181108_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guidedesign',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guideselection',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primerdesign',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primerselection',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researcher',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='targets_raw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=65536, validators=[utils.validators.validate_chr_or_seq_or_enst_or_gene]), default=['ENST00000617316,N', 'ENST00000278840,C', 'ENST00000638572,N', 'ENST00000361781,C', 'ENST00000317551,C', 'ENST00000460006,N', 'ENST00000323646,N', 'ENST00000300737,C', 'ENST00000356978,N', 'ENST00000325110,C', 'ENST00000287936,C', 'ENST00000228510,C', 'ENST00000368467,N', 'ENST00000301012,C', 'ENST00000381344,C', 'ENST00000282841,C', 'ENST00000220584,C', 'ENST00000265896,N', 'ENST00000430767,C', 'ENST00000356396,C', 'ENST00000450723,C', 'ENST00000279263,N', 'ENST00000261507,C', 'ENST00000352397,C', 'ENST00000370274,N', 'ENST00000495186,C', 'ENST00000264027,C', 'ENST00000355527,N', 'ENST00000371269,C', 'ENST00000216484,C', 'ENST00000406396,C', 'ENST00000623882,C', 'ENST00000271688,C', 'ENST00000251363,C', 'ENST00000323699,C', 'ENST00000374279,C', 'ENST00000306851,N', 'ENST00000341156,N', 'ENST00000394684,C', 'ENST00000351288,N', 'ENST00000323374,C', 'ENST00000245222,C', 'ENST00000247225,N', 'ENST00000321276,N', 'ENST00000373202,C', 'ENST00000216264,N', 'ENST00000352035,C', 'ENST00000306749,C', 'ENST00000372458,C', 'ENST00000354666,C', 'ENST00000369816,C', 'ENST00000304434,C', 'ENST00000394607,C', 'ENST00000508821,C', 'ENST00000370355,C', 'ENST00000319540,C', 'ENST00000350997,C', 'ENST00000278829,C', 'ENST00000611707,C', 'ENST00000396987,C', 'ENST00000371696,C', 'ENST00000398063,C', 'ENST00000320285,C', 'ENST00000285518,C', 'ENST00000302182,N', 'ENST00000283415,N', 'ENST00000262134,N', 'ENST00000261407,C', 'ENST00000314891,N', 'ENST00000305997,C', 'ENST00000245615,C', 'ENST00000366997,C', 'ENST00000264775,C', 'ENST00000371250,C', 'ENST00000424479,C', 'ENST00000381883,C', 'ENST00000295887,N', 'ENST00000545121,N', 'ENST00000219789,C', 'ENST00000229266,N', 'ENST00000517309,N', 'ENST00000308020,N', 'ENST00000367466,C', 'ENST00000539276,C', 'ENST00000374316,N', 'ENST00000283006,C', 'ENST00000447750,C', 'ENST00000380191,c', 'ENST00000306480,C', 'ENST00000268607,N', 'ENST00000377190,C', 'ENST00000358901,N', 'ENST00000274140,C'], help_text='Chromosome location, fasta sequence, ENST transcript ID, or\n            gene name. One per line. Append ",N" or ",C" to a line to tag at N or\n            C terminus.', size=None, validators=[utils.validators.validate_unique_set], verbose_name='Target regions'),
        ),
    ]
