# Generated by Django 2.1.1 on 2018-11-15 23:32

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181114_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='is_hdr',
            field=models.BooleanField(default=True, help_text='Insert a sequence by HDR (Homology Directed Repair)', verbose_name='HDR experiment?'),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='guides_per_target',
            field=models.IntegerField(default=1, help_text='The top N number of guides per target to select.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(96)]),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='hdr_start_codon_tag_seq',
            field=models.CharField(blank=True, default='ACCGAGCTCAACTTCAAGGAGTGGCAAAAGGCCTTTACCGATATGATGGGTGGCGGATTGGAAGTTTTGTTTCAAGGTCCAGGAAGTGGT', help_text='Sequence of tag to insert just after start codon', max_length=65536, validators=[utils.validators.validate_seq, django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(90)], verbose_name='Tag sequence for start codon'),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='hdr_stop_codon_tag_seq',
            field=models.CharField(blank=True, default='GGTGGCGGATTGGAAGTTTTGTTTCAAGGTCCAGGAAGTGGTACCGAGCTCAACTTCAAGGAGTGGCAAAAGGCCTTTACCGATATGATG', help_text='Sequence of tag to insert just before stop codon', max_length=65536, validators=[utils.validators.validate_seq, django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(90)], verbose_name='Tag sequence for stop codon'),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='hdr_tag',
            field=models.CharField(blank=True, choices=[('start_codon', 'Within 36bp before or after start codon (N-terminus)'), ('stop_codon', 'Within 36bp before or after stop codon (C-terminus)'), ('per_target', 'Within 36bp before or after, terminus specified per target ("N" or "C")')], default='per_target', help_text='Where to insert the tag in each gene', max_length=40, verbose_name='HDR tag terminus'),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='target_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('start_codon', 'Within 36bp before or after start codon (N-terminus)'), ('stop_codon', 'Within 36bp before or after stop codon (C-terminus)'), ('per_target', 'Within 36bp before or after, terminus specified per target ("N" or "C")')], max_length=40), blank=True, size=None, verbose_name='Target HDR tags'),
        ),
    ]
