# Generated by Django 2.1 on 2018-08-16 18:45

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180810_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidedesign',
            name='target_seqs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=65536, validators=[main.validators.validate_seq]), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='donor_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Data returned by external service'),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='guide_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Data returned by external service'),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='targets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=65536, validators=[main.validators.validate_chr_or_seq_or_enst_or_gene]), default=['chr2:38377365-38377424', 'chr11:63671410-63671469', 'chrX:153701031-153701090', 'chr14:75657546-75657605', 'chr14:75651664-75651723', 'chr14:23097577-23097636', 'chr14:23097913-23097972', 'chr15:67521137-67521196', 'chr15:67526436-67526495', 'chr18:35972616-35972675', 'chr18:35978838-35978897', 'chr19:1275474-1275533', 'chr19:1277214-1277273', 'chr19:12734688-12734747', 'chr19:12731029-12731088', 'chr19:13774309-13774368', 'chr19:13778035-13778094', 'chr1:53220672-53220731', 'chr1:53214723-53214782', 'chr21:32612313-32612372', 'chr21:32601953-32602012', 'chr7:1127420-1127479', 'chr7:997684-997743', 'chr7:135662408-135662467', 'chr7:135674007-135674066', 'chr8:145052416-145052475', 'chr8:145054080-145054139', 'chr8:85217610-85217669', 'chr8:85214589-85214648', 'chr9:128160324-128160383', 'chr9:128163437-128163496', 'chr9:27567182-27567241', 'chr12:55728387-55728446', 'chr11:2377415-2377474', 'chr12:6200379-6200438', 'chr9:36190899-36190958', 'chr5:176416441-176416500', 'chr17:59693711-59693770', 'chr5:75379392-75379451', 'chr12:56128228-56128287', 'chr6:29945285-29945344', 'chr1:11258674-11258733', 'chr2:189771810-189771869', 'chr12:55820298-55820357', 'chr17:39922620-39922679', 'chr11:59615778-59615837', 'chr3:125594895-125594954', 'chr12:76487647-76487706', 'chr2:26034454-26034513', 'chr15:65869483-65869542', 'chr19:8390321-8390380', 'chr18:8609599-8609658', 'chr1:153986256-153986315', 'chr9:121193466-121193525', 'chr10:27504201-27504260', 'chr2:65130036-65130095', 'chr11:66268524-66268583', 'chr12:71754963-71755022', 'chr6:57210498-57210557', 'chr5:177303351-177303410', 'chr4:13484196-13484255', 'chr1:205775078-205775137', 'chr8:60517056-60517115', 'chr14:21476978-21477037', 'chr6:146543708-146543767', 'chr4:139454092-139454151', 'chr12:120116667-120116726', 'chr19:11337445-11337504', 'chr1:220272441-220272500', 'chr17:82698716-82698775', 'chr16:590214-590273', 'chr3:19950819-19950878', 'chr12:55986864-55986923', 'chr3:133895555-133895614', 'chr3:128795279-128795338', 'chr15:63189444-63189503', 'chrX:13708616-13708675', 'chr19:41959405-41959464', 'chr17:5282310-5282369', 'chr9:125202921-125202980', 'chr9:122956944-122957003', 'chr1:174219010-174219069', 'chr14:24271141-24271200', 'chr1:75786089-75786148', 'chr1:202889114-202889173', 'chr3:120742615-120742674', 'chr7:151519523-151519582', 'chr2:55050409-55050468', 'chr3:45703309-45703368', 'chr9:99222443-99222502', 'chr4:89726670-89726729', 'chr9:92032520-92032579', 'chr14:34462221-34462280', 'chr18:9914152-9914211', 'chr20:58389364-58389423'], help_text='Chr location, seq, ENST, or gene. One per line.', size=None),
        ),
        migrations.AlterField(
            model_name='primerdesign',
            name='primer_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Data returned by external service'),
        ),
    ]
