# Generated by Django 2.0.7 on 2018-07-13 08:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180710_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideselection',
            name='guide_data',
        ),
        migrations.AddField(
            model_name='guidedesign',
            name='guide_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='PAM',
            field=models.CharField(choices=[('NGG', '20bp-NGG - Sp Cas9, SpCas9-HF1, eSpCas9 1.1'), ('todo', 'TODO: more PAMs')], default='NGG', max_length=80),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='genome',
            field=models.CharField(choices=[('hg19', 'Homo sapiens - Human - UCSC Feb. 2009 (GRCh37/hg19) + SNPs: 1000Genomes, ExaC'), ('todo', 'TODO: more genomes')], default='hg19', max_length=80),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='targets',
            field=models.CharField(max_length=65536, validators=[main.validators.validate_chr_or_seq]),
        ),
    ]
