# Generated by Django 2.1.1 on 2018-11-16 00:44

import django.core.validators
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181115_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='description',
            field=models.CharField(blank=True, help_text='Friendly description for other people', max_length=65536),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='name',
            field=models.CharField(help_text='Identifying name of the experiment', max_length=40),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='hdr_start_codon_tag_seq',
            field=models.CharField(default='ACCGAGCTCAACTTCAAGGAGTGGCAAAAGGCCTTTACCGATATGATGGGTGGCGGATTGGAAGTTTTGTTTCAAGGTCCAGGAAGTGGT', help_text='Sequence of tag to insert just after start codon', max_length=65536, null=True, validators=[utils.validators.validate_seq, django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(90)], verbose_name='Tag sequence for start codon'),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='hdr_stop_codon_tag_seq',
            field=models.CharField(default='GGTGGCGGATTGGAAGTTTTGTTTCAAGGTCCAGGAAGTGGTACCGAGCTCAACTTCAAGGAGTGGCAAAAGGCCTTTACCGATATGATG', help_text='Sequence of tag to insert just before stop codon', max_length=65536, null=True, validators=[utils.validators.validate_seq, django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(90)], verbose_name='Tag sequence for stop codon'),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='hdr_tag',
            field=models.CharField(choices=[('start_codon', 'Within 36bp before or after start codon (N-terminus)'), ('stop_codon', 'Within 36bp before or after stop codon (C-terminus)'), ('per_target', 'Within 36bp before or after, terminus specified per target ("N" or "C")')], default=None, help_text='Where to insert the tag in each gene', max_length=40, null=True, verbose_name='HDR tag terminus'),
        ),
    ]
