# Generated by Django 2.1 on 2018-08-16 19:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import functools
import main.models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180816_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideselection',
            name='selected_guides',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='sgRNAs from crispor.tefor.net', validators=[main.validators.validate_num_wells, main.models.GuideSelection._validate_selected_guides]),
        ),
        migrations.AlterField(
            model_name='primerselection',
            name='selected_primers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Primers from crispor.tefor.net', validators=[functools.partial(main.validators.validate_num_wells, *(), **{'max': 192}), main.models.PrimerSelection._validate_selected_primers]),
        ),
    ]
