# Generated by Django 2.1 on 2018-08-08 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180807_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='amplicon_seq',
        ),
    ]
