# Generated by Django 2.0.7 on 2018-07-14 01:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180713_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideselection',
            name='is_selected',
        ),
        migrations.AddField(
            model_name='guideselection',
            name='selected_guides',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='guide_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
