# Generated by Django 2.1.1 on 2018-11-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181112_1521'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='researcher',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='owner',
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='genome',
            field=models.CharField(choices=[(
                'hg38', 'Homo sapiens - Human - UCSC Dec. 2013 (GRCh38/hg38)')], default='hg38', max_length=80),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='hdr_tag',
            field=models.CharField(blank=True, choices=[('start_codon', 'Within 36bp after start codon (N-terminus)'), ('stop_codon', 'Within 36bp before or after stop codon (C-terminus)'), (
                'per_target', 'As specified per target ("N" or "C")')], help_text='Insert a sequence by HDR (Homology Directed Repair). Requires ENST transcript IDs.', max_length=40, verbose_name='Insert tag by HDR'),
        ),
        migrations.DeleteModel(
            name='Researcher',
        ),
    ]
