# Generated by Django 2.1.1 on 2018-09-05 18:55

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180816_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='guidedesign',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='guideselection',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='primerdesign',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='primerselection',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='analysis',
            name='fastqs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=160, validators=[main.validators.validate_fastq]), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='results_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Data returned by external service'),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='genome',
            field=models.CharField(choices=[('hg38', 'Homo sapiens - Human - UCSC Dec. 2013 (GRCh38/hg38) + SNPs: dbSNP148, Kaviar'), ('hg19', 'Homo sapiens - Human - UCSC Feb. 2009 (GRCh37/hg19) + SNPs: 1000Genomes, ExaC'), ('todo', 'TODO: more genomes')], default='hg38', max_length=80),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='targets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=65536, validators=[main.validators.validate_chr_or_seq_or_enst_or_gene]), default=['chr2:38377154-38377424', 'chr11:63671209-63671469', 'chrX:153700826-153701090', 'chr14:75657356-75657605', 'chr14:75651474-75651723', 'chr14:23097577-23097833', 'chr14:23097913-23098179', 'chr15:67521137-67521414', 'chr15:67526436-67526700', 'chr18:35972616-35972885', 'chr18:35978838-35979107', 'chr19:1275474-1275724', 'chr19:1277214-1277466', 'chr19:12734478-12734747', 'chr19:12730836-12731088', 'chr19:13774309-13774571', 'chr19:13778035-13778297', 'chr1:53220476-53220731', 'chr1:53214523-53214782', 'chr21:32612122-32612372', 'chr21:32601760-32602012', 'chr7:1127213-1127479', 'chr7:997489-997743', 'chr7:135662408-135662673', 'chr7:135674007-135674269', 'chr8:145052416-145052678', 'chr8:145054080-145054341', 'chr8:85217405-85217669', 'chr8:85214399-85214648', 'chr9:128160324-128160593', 'chr9:128163437-128163702', 'chr9:27566981-27567241', 'chr12:55728192-55728446', 'chr11:2377415-2377673', 'chr12:6200379-6200636', 'chr9:36190899-36191152', 'chr5:176416251-176416500', 'chr17:59693711-59693960', 'chr5:75379177-75379451', 'chr12:56128228-56128494', 'chr6:29945285-29945542', 'chr1:11258474-11258733', 'chr2:189771618-189771869', 'chr12:55820298-55820562', 'chr17:39922414-39922679', 'chr11:59615570-59615837', 'chr3:125594704-125594954', 'chr12:76487443-76487706', 'chr2:26034454-26034708', 'chr15:65869483-65869736', 'chr19:8390321-8390591', 'chr18:8609599-8609871', 'chr1:153986059-153986315', 'chr9:121193263-121193525', 'chr10:27504201-27504465', 'chr2:65129826-65130095', 'chr11:66268524-66268773', 'chr12:71754963-71755230', 'chr6:57210282-57210557', 'chr5:177303154-177303410', 'chr4:13483981-13484255', 'chr1:205774862-205775137', 'chr8:60517056-60517321', 'chr14:21476777-21477037', 'chr6:146543708-146543974', 'chr4:139454092-139454365', 'chr12:120116450-120116726', 'chr19:11337255-11337504', 'chr1:220272247-220272500', 'chr17:82698506-82698775', 'chr16:590214-590472', 'chr3:19950819-19951070', 'chr12:55986864-55987121', 'chr3:133895363-133895614', 'chr3:128795279-128795541', 'chr15:63189444-63189718', 'chrX:13708616-13708872', 'chr19:41959204-41959464', 'chr17:5282310-5282588', 'chr9:125202921-125203181', 'chr9:122956944-122957210', 'chr1:174219010-174219265', 'chr14:24270935-24271200', 'chr1:75786089-75786358', 'chr1:202888904-202889173', 'chr3:120742415-120742674', 'chr7:151519312-151519582', 'chr2:55050218-55050468', 'chr3:45703309-45703572', 'chr9:99222443-99222712', 'chr4:89726465-89726729', 'chr9:92032330-92032579', 'chr14:34462021-34462280', 'chr18:9914152-9914417', 'chr20:58389364-58389613'], help_text='Chr location, seq, ENST, or gene. One per line.', size=None),
        ),
    ]
