# Generated by Django 2.1.1 on 2018-10-04 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181004_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideselection',
            name='selected_guides_tagin',
        ),
    ]
