# Generated by Django 2.0.7 on 2018-07-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180713_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidedesign',
            name='PAM',
        ),
        migrations.RemoveField(
            model_name='primerdesign',
            name='amplicon_size',
        ),
        migrations.RemoveField(
            model_name='primerdesign',
            name='length',
        ),
        migrations.RemoveField(
            model_name='primerdesign',
            name='location',
        ),
        migrations.RemoveField(
            model_name='primerdesign',
            name='melting_temp',
        ),
        migrations.RemoveField(
            model_name='primerdesign',
            name='primers_per_guide',
        ),
        migrations.AddField(
            model_name='guidedesign',
            name='pam',
            field=models.CharField(choices=[('NGG', '20bp-NGG - Sp Cas9, SpCas9-HF1, eSpCas9 1.1'), ('todo', 'TODO: more pams')], default='NGG', max_length=80),
        ),
        migrations.AddField(
            model_name='primerdesign',
            name='maximum_amplicon_length',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='primerdesign',
            name='pam',
            field=models.CharField(choices=[('NGG', '20bp-NGG - Sp Cas9, SpCas9-HF1, eSpCas9 1.1'), ('todo', 'TODO: more pams')], default='NGG', max_length=80),
        ),
        migrations.AddField(
            model_name='primerdesign',
            name='pam_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='primerdesign',
            name='primer_temp',
            field=models.IntegerField(default=60),
        ),
    ]
