# Generated by Django 2.1.1 on 2018-11-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181126_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidedesign',
            name='hdr_tag',
            field=models.CharField(blank=True, choices=[('start_codon', 'Within 96 before or after start codon (N-terminus)'), ('stop_codon', 'Within 96 before or after stop codon (C-terminus)'), ('per_target', 'Within 96 before or after, terminus specified per target ("N" or "C")')], default='per_target', help_text='Where to insert the tag in each gene', max_length=40, null=True, verbose_name='HDR tag terminus'),
        ),
    ]
