# Generated by Django 2.1.1 on 2018-10-08 23:05

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_guideselection_selected_guides_tagin'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidedesign',
            name='targets_raw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=65536, validators=[main.validators.validate_chr_or_seq_or_enst_or_gene]), default=[
            ], help_text='Chr location, seq, ENST, or gene. One per line. For reverse strand, write chr location right-to-left.', size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='hdr_tag',
            field=models.CharField(blank=True, choices=[('start_codon', 'Within 40bp of Start Codon'), (
                'stop_codon', 'Within 40bp of Stop Codon')], help_text='Insert GFP (Green Fluorescent Protein) by HDR (Homology Directed Repair)', max_length=40),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='pam',
            field=models.CharField(
                choices=[('NGG', '20bp-NGG (SpCas9, SpCas9-HF1, eSpCas9, ...)')], default='NGG', max_length=80),
        ),
        migrations.AlterField(
            model_name='guidedesign',
            name='targets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(
                blank=True, max_length=80, validators=[main.validators.validate_chr]), size=None),
        ),
        migrations.AlterField(
            model_name='primerdesign',
            name='max_amplicon_length',
            field=models.IntegerField(default=400, validators=[django.core.validators.MinValueValidator(
                200), django.core.validators.MaxValueValidator(400)]),
        ),
    ]
