# Generated by Django 2.0.7 on 2018-07-15 02:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180713_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='primerdesign',
            name='primer_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
