# Generated by Django 2.0.7 on 2018-07-15 05:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_primerdesign_primer_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primerselection',
            name='is_selected',
        ),
        migrations.RemoveField(
            model_name='primerselection',
            name='primer_data',
        ),
        migrations.AddField(
            model_name='primerselection',
            name='selected_primers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
