# Generated by Django 2.1.1 on 2018-12-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181204_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='demultiplex',
            field=models.BooleanField(blank=True, default=False, help_text="De-multiplex FastQ files into samples by matching primers\n            to the beginning and end of each read. This is useful if the samples\n            were *not* indexed before sequencing. The samples must each have a\n            unique pair of forward and reverse primers. Reads that don't match\n            any pair will be discarded, typically less than 5%."),
        ),
    ]
