# Generated by Django 2.0.7 on 2018-07-16 01:28

from django.db import migrations, models
import django.db.models.deletion
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180714_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_selection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.GuideSelection')),
                ('primer_selection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.PrimerSelection')),
            ],
        ),
        migrations.AddField(
            model_name='guidedesign',
            name='hdr_seq',
            field=models.CharField(blank=True, max_length=65536, null=True, validators=[main.validators.validate_chr_or_seq]),
        ),
    ]
