# Generated by Django 2.1.1 on 2019-01-07 22:50

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_analysis_demultiplex'),
    ]

    operations = [
        migrations.AddField(
            model_name='primerdesign',
            name='adapter_seq',
            field=models.CharField(default='AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT', help_text='The DNA sequence that is prepended to each primer for deep sequencing (NGS). The default is the Illumina universal adapter.', max_length=160, validators=[utils.validators.validate_seq], verbose_name='Adapter Sequence'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='demultiplex',
            field=models.BooleanField(blank=True, default=False, help_text="De-multiplex FastQ files into samples by matching primers\n            to the beginning and end of each read. This is useful if the samples\n            were *not* indexed before sequencing. The samples must each have a\n            unique pair of forward and reverse primers. Reads that don't match\n            any pair will be discarded, typically less than 5%. Warning:\n            demultiplexing is slow! It may take up to 30 min for a full 96-well\n            plate."),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='s3_bucket',
            field=models.CharField(default='jasonli-bucket', help_text='The Amazon S3 bucket that contains the FastQ files to be\n        analyzed. If you do not have access to a Biohub or public s3 bucket,\n        please contact gdingle@chanzuckerberg.com for assistance.', max_length=80),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='s3_prefix',
            field=models.CharField(default='CrispyCrunch', help_text='The S3 directory that contains the FastQ files to be\n        analyzed. Files are assumed to be paired-end reads––two files, R1 and\n        R2, per sample (unless demultiplexing).', max_length=160),
        ),
    ]
