# Generated by Django 2.1.1 on 2019-01-09 23:34

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190107_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primerdesign',
            name='adapter_seq',
        ),
        migrations.AddField(
            model_name='primerdesign',
            name='adapter_seq_left',
            field=models.CharField(default='CTACACGACGCTCTTCCGATCT', help_text="The DNA sequence that is prepended to the left primer in 5' to\n            3' direction for deep sequencing (NGS).", max_length=160, validators=[utils.validators.validate_seq], verbose_name='Left Adapter sequence'),
        ),
        migrations.AddField(
            model_name='primerdesign',
            name='adapter_seq_right',
            field=models.CharField(default='AGACGTGTGCTCTTCCGATCT', help_text="The DNA sequence that is prepended to the right primer in 5' to\n            3' direction for deep sequencing (NGS).", max_length=160, validators=[utils.validators.validate_seq], verbose_name='Right Adapter sequence'),
        ),
    ]
