# Generated by Django 2.1.1 on 2019-01-24 20:20

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190109_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='primerdesign',
            name='adapter_name',
            field=models.CharField(blank=True, choices=[('', 'No Trimming'), ('NexteraPE-PE.fa', 'Nextera PE'), ('TruSeq3-PE.fa', 'TruSeq3 PE'), ('TruSeq3-SE.fa', 'TruSeq3 SE'), ('TruSeq2-PE.fa', 'TruSeq2 PE'), ('TruSeq2-SE.fa', 'TruSeq2 SE')], default='TruSeq3-PE.fa', help_text='What adapter to tell trimmomatic to trim from your FastQs\n        before analysis. This should be compatible with the sequences above.', max_length=40, verbose_name='Adapter name (for trimmomatic)'),
        ),
        migrations.AlterField(
            model_name='primerdesign',
            name='adapter_seq_left',
            field=models.CharField(default='CTACACGACGCTCTTCCGATCT', help_text="The DNA sequence that is prepended to the left (forward)\n            primer in 5' to 3' direction for deep sequencing (NGS). Default is TruSeq3 PE compatible.", max_length=160, validators=[utils.validators.validate_seq], verbose_name='Left adapter sequence'),
        ),
        migrations.AlterField(
            model_name='primerdesign',
            name='adapter_seq_right',
            field=models.CharField(default='AGACGTGTGCTCTTCCGATCT', help_text="The DNA sequence that is prepended to the right (reverse)\n            primer in 5' to 3' direction for deep sequencing (NGS). Default is TruSeq3 PE compatible.", max_length=160, validators=[utils.validators.validate_seq], verbose_name='Right adapter sequence'),
        ),
    ]
